### ISSUE TITLE
How EOS know where to send stream?

### ISSUE THREAD

**Issue by ljyfree** [arista-netdevops-community/arista_eos_streaming_telemetry_with_gnmi_and_telegraf#6]
Hi all
    
    I could not find configuration for EOS about Telegraf's IP address and Listen port.
    So how EOS know where to send stream?

**Comment by ksator** [comment]
Hello, 
EOS runs a gNMI server.  
Telegraf runs a gNMI client.  
No need to configure the clients IP addresses in a server, so, no need to configure Telegraf IP address in EOS.  
Telegraf sends a subscribtion request to EOS which is a TCP communication.
